name: Dev Container Image Development

on:
  pull_request:
    branches:
      - 'main'
      - 'release/*'
    paths:
      - 'dev.Dockerfile'
      - '.github/workflows/image-development.yaml'

jobs:
  check-image:
    name: Validate Dev Container Build
    runs-on: ubuntu-latest
    steps:
      - name: Run actions/checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - name: Run docker/setup-buildx-action
        uses: docker/setup-buildx-action@8d2750c68a42422c14e847fe6c8ac0403b4cbd6f # v3
      - name: Build image
        uses: docker/build-push-action@601a80b39c9405e50806ae38af30926f9d957c47 # v6
        with:
          context: .
          file: ./dev.Dockerfile
          push: false
